name: Release Drafter

on:
  workflow_dispatch:
    inputs:
      release_commitish:
        description: 'Commitish to use for drafting notes'
        required: false
        type: string
        default: 'main'
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      pull-requests: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          commitish: ${{ github.event.inputs.release_commitish || 'main' }}
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
